kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.activegate.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ .Values.activegate.serviceAccountName }}
    verbs:
      - use