# Copyright 2019 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-activegate-operator.labels" . | nindent 4 }}
  annotations:
    kubernetes-engine.cloud.google.com/icon: data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "dynatrace-marketplace-prod", "product_id": "dynatrace-activegate-operator", "partner_name": "Dynatrace LLC"}'
spec:
  descriptor:
    type: "Dynatrace ActiveGate Operator"
    version: "0.1.0"
    maintainers:
      - name: Dynatrace LLC
        url: https://www.dynatrace.com/
    keywords:
      - "dynatrace"
      - "operator"
      - "activegate"
      - "k8s"
      - "monitoring"
      - "apm"
    description: |
      ToDo
    links:
      - description: Dynatrace Website
        url: https://www.dynatrace.com/
      - description: Operator Deploy Guide
        url: ToDo
      - description: Kubernetes Monitoring Info
        url: https://www.dynatrace.com/technologies/kubernetes-monitoring

    links:
      - description: Dynatrace Website
        url: https://www.dynatrace.com/
      - description: Operator Deploy Guide
        url: ToDo
      - description: Kubernetes Monitoring Info
        url: https://www.dynatrace.com/technologies/kubernetes-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
    - group: v1
      kind: Pod
    - group: v1
      kind: ConfigMap
    - group: apps/v1
      kind: Deployment
    - group: v1
      kind: Secret
    - group: batch/v1
      kind: Job
