# Copyright 2020 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "0.2.1"
  publishedVersionMetadata:
    releaseNote: >-
      v0.2.1

      Features
      * classicFullStack - The Dynatrace Operator now supports rolling out a fullstack agent
      * routing - The Dynatrace Operator now supports rolling out a containerized ActiveGate to route the agent traffic

      Bug fixes
      * Fixed a bug where setting resource limits for routing did not work
    releaseTypes:
      - Feature
    recommended: true

  managedUpdates:
    kalmSupported: true

  images:
    "":
      properties:
        operator.image:
          type: FULL
  deployerServiceAccount:
    description: >
      Service account used to configure the Dynatrace Operator
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
              - admissionregistration.k8s.io
            resources:
              - mutatingwebhookconfigurations
            verbs:
              - get
              - create
              - list
              - patch
          - apiGroups:
              - dynatrace.com
            resources:
              - dynakubes
            verbs:
              - get
              - list
              - create
              - patch
          - apiGroups:
              - apiextensions.k8s.io
            resources:
              - customresourcedefinitions
            verbs:
              - get
              - list
              - create
              - patch
          - apiGroups:
              - dynatrace.com
            resources:
              - dynakubes
            verbs:
              - get
              - list
              - watch
              - update
              - patch
          - apiGroups:
              - app.k8s.io
            resources:
              - applications
            verbs:
              - get
              - list
          - apiGroups:
              - storage.k8s.io
            resources:
              - csidrivers
            verbs: ["*"]
          - apiGroups: [""]
            resources:
              - services
              - serviceaccounts
            verbs: ["*"]
          - apiGroups:
              - rbac.authorization.k8s.io
            resources:
              - role
              - rolebinding
              - clusterroles
              - clusterrolebindings
            verbs: ["*"]
          - apiGroups:
              - admissionregistration.k8s.io
            resources:
              - validatingwebhookconfigurations
            verbs: ["*"]

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  apiUrl:
    type: string
    description: The Dynatrace api url including `/api` path at the end
    title: API URL
  apiToken:
    type: string
    description: The API token from your Dynatrace environment
    title: API Token
    x-google-marketplace:
      type: MASKED_FIELD
  paasToken:
    type: string
    description: The PaaS token from your Dynatrace environment
    title: PaaS Token
    x-google-marketplace:
      type: MASKED_FIELD
  autoCreateSecret:
    type: boolean
    description: "Enable if you want to automatically create a secret from your api-token and paas-token"
    title: "Automatically create token-secret"
    default: true
  crdApplied:
    type: boolean
    description: "Please make sure you have applied the latest CRD by following the instructions in the Github Repository."
    title: "CRD manually applied"
    default: false

  customPullSecret:
    type: string
    description: "Sets the name of the pull secret that should be used"
    title: "Custom pull secret"
  skipCertCheck:
    type: boolean
    description: "Disable certificate validation checks for installer download and API communication"
    default: false
    title: "Skip certificate check"
  proxy:
    type: string
    description: "Configures a proxy for the Agent, AgentDownload, ActiveGate and the Operator. Either provide the proxy URL directly at 'value' or create a secret with a field 'proxy' which holds your encrypted proxy URL"
    title: "Define a proxy"
  trustedCAs:
    type: string
    description: "Adds the provided CA certificates to the Operator and the OneAgent. Provide the name of the configmap which holds your .pem in a field called 'certs'. If this is not set the default embedded certificates on the images will be used"
    title: "Add custom CA certificates"
  networkZone:
    type: string
    description: "Sets a network zone for the given OneAgent or ActiveGates"
    title: "Network zone"
  enableIstio:
    type: boolean
    description: "When enabled, and if Istio is installed on the Kubernetes environment, then the Operator will create the corresponding VirtualService and ServiceEntry objects to allow access to the Dynatrace cluster from the agent or the activeGate"
    title: "Enable Istio"
  platform:
    type: string
    title: The platform you are deploying on
    description: This should always be set to "google"
    default: google

  operator.image:
    type: string
    description: "The location from where to grab the Dynatrace Operator image"
    title: "Operator image"
  operator.nodeSelector:
    type: string
    description: "Node selector to control on which nodes the opertor will be deployed"
    title: "Operator node selector"
  operator.tolerations:
    type: string
    description: "Set which node taints the operator deployment tolerates"
    title: "Operator tolerations"

  activeGate.image:
    type: string
    description: "The location from where to grab the Dynatrace ActiveGate image - default for Kubernetes is ToDo"
    title: "Custom ActiveGate image location"
  activeGate.autoUpdate:
    type: boolean
    description: "Enable automatic restarts of ActiveGate pods in case a new version is available"
    default: true
    title: "Enable automatic ActiveGate updates"

  oneAgent.version:
    type: string
    description: "The version of the OneAgent to be used when useImmutableImage is enabled"
    title: "OneAgent version"
  oneAgent.image:
    type: string
    description: "Set to use a custom OneAgent Docker image"
    title: "OneAgent image"
  oneAgent.autoUpdate:
    type: boolean
    description: "Enables automatic restarts of oneagent pods in case a new version is available"
    title: "Automatically update OneAgent"
    default: true

  codeModules.enabled:
    type: boolean
    description: "Enable code modules"
    title: "Enable code modules"
  codeModules.volume:
    type: string
    description: |
      Define a volume the OneAgent binary will be taken from.
      Two options are currently supported.
      By default, the Dynatrace CSI driver will be used to provide a volume.
      When using an emptyDir, the previous approach using init containers and wget will be used.
    title: "CodeModules volume"
  codeModules.resources:
    type: string
    description: "Resource settings for the init-container"
    title: "CodeModules resources"
  codeModules.selector:
    type: string
    description: "Set the label selector to define which namespaces to inject into"
    title: "CodeModules selector"

  infraMonitoring.enabled:
    type: boolean
    description: "Enable infrastructure monitoring"
    title: "Enable infrastructure monitoring"
  infraMonitoring.nodeSelector:
    type: string
    description: "Set node selector to control on which nodes the OneAgent will be deployed"
    title: "Infra node selector"
  infraMonitoring.tolerations:
    type: string
    description: "Tolerations to include with the OneAgent DaemonSet"
    title: "Infra tolerations"
  infraMonitoring.resources:
    type: string
    description: "Resource settings for OneAgent container"
    title: "Infra resources"
  infraMonitoring.args:
    type: string
    description: "Arguments to add to the OneAgent installer"
    title: "Infra arguments"
  infraMonitoring.env:
    type: string
    description: "Additional environment variables to add to the OneAgent Pods"
    title: "Infra environment variables"
  infraMonitoring.priorityClassName:
    type: string
    description: "Priority class to assign to the OneAgent Pods"
    title: "Infra priority class name"
  infraMonitoring.dnsPolicy:
    type: string
    description: "DNS Policy for OneAgent pods"
    title: "Infra DNS policy"
    default: "ClusterFirstWithHostNet"
    enum:
      - "Default"
      - "ClusterFirst"
      - "ClusterFirstWithHostNet"
      - "None"
  infraMonitoring.serviceAccountName:
    type: string
    description: "Name of the ServiceAccount to assign to the OneAgent Pods"
    title: "Infra service-account name"
  infraMonitoring.labels:
    type: string
    description: "Labels are customer defined labels for OneAgent Pods to structure workloads as desired"
    title: "Infra labels"
  infraMonitoring.useUnprivilegedMode:
    type: boolean
    description: "When enabled the OneAgent Pods will run as unprivileged pods"
    title: "Infra use unprivileged mode"
    default: true
  infraMonitoring.useImmutableImage:
    type: boolean
    description: "if enabled, the Operator will use the immutable image from the Dynatrace environment or from your custom registry, otherwise an installer image is used"
    title: "Infra use immutable image"

  classicFullStack.enabled:
    type: boolean
    description: "Enable classic oneagent monitoring"
    title: "Enable classic fullstack monitoring"
  classicFullStack.nodeSelector:
    type: string
    description: "Set node selector to control on which nodes the OneAgent will be deployed"
    title: "Classic node selector"
  classicFullStack.tolerations:
    type: string
    description: "Tolerations to include with the OneAgent DaemonSet"
    title: "Classic tolerations"
  classicFullStack.resources:
    type: string
    description: "Resource settings for OneAgent container"
    title: "Classic resources"
  classicFullStack.args:
    type: string
    description: "Arguments to add to the OneAgent installer"
    title: "Classic arguments"
  classicFullStack.env:
    type: string
    description: "Additional environment variables to add to the OneAgent Pods"
    title: "Classic environment variables"
  classicFullStack.priorityClassName:
    type: string
    description: "Priority class to assign to the OneAgent Pods"
    title: "Classic priority class name"
  classicFullStack.dnsPolicy:
    type: string
    description: "DNS Policy for OneAgent pods"
    title: "Classic DNS policy"
    default: "ClusterFirstWithHostNet"
    enum:
      - "Default"
      - "ClusterFirst"
      - "ClusterFirstWithHostNet"
      - "None"
  classicFullStack.serviceAccountName:
    type: string
    description: "Name of the ServiceAccount to assign to the OneAgent Pods"
    title: "Classic service-account name"
  classicFullStack.labels:
    type: string
    description: "Labels are customer defined labels for OneAgent Pods to structure workloads as desired"
    title: "Classic labels"
  classicFullStack.useUnprivilegedMode:
    type: boolean
    description: "When enabled the OneAgent Pods will run as unprivileged pods"
    title: "Classic use unprivileged mode"
    default: true
  classicFullStack.useImmutableImage:
    type: boolean
    description: "if enabled, the Operator will use the immutable image from the Dynatrace environment or from your custom registry, otherwise an installer image is used"
    title: "Classic use immutable image"

  kubernetesMonitoring.enabled:
    type: boolean
    description: "Enables automatic Kubernetes monitoring for your cluster"
    title: "Enable Kubernetes monitoring (Kubemon)"
    default: true
  kubernetesMonitoring.replicas:
    type: integer
    description: "Number of replicas for the Kubernetes monitoring pods"
    title: "Kubemon Replicas"
    default: 1
  kubernetesMonitoring.group:
    type: string
    description: "Set activation group for this ActiveGate"
    title: "Kubemon activation group"
  kubernetesMonitoring.customProperties.value:
    type: string
    description: "Add a custom properties file by providing it as a value"
    title: "Kubemon custom properties as value"
  kubernetesMonitoring.customProperties.valueFrom:
    type: string
    description: "Add a custom properties file by providing it as a reference"
    title: "Kubemon custom properties as reference"
  kubernetesMonitoring.resources:
    type: string
    description: "Resource settings for ActiveGate container"
    title: "Kubemon resources"
  kubernetesMonitoring.nodeSelector:
    type: string
    description: "Set node selector to control on which nodes these ActiveGate pods will be deployed"
    title: "Kubemon node selector"
  kubernetesMonitoring.tolerations:
    type: string
    description: "Tolerations to include with this ActiveGate StatefulSet"
    title: "Kubemon tolerations"
  kubernetesMonitoring.labels:
    type: string
    description: "Labels are customer defined labels for these ActiveGate Pods to structure workloads as desired"
    title: "Kubemon labels"
  kubernetesMonitoring.args:
    type: string
    description: "Arguments to add to these ActiveGate instances"
    title: "Kubemon arguments"
  kubernetesMonitoring.env:
    type: string
    description: "Additional environment variables to add to these ActiveGate Pods"
    title: "Kubemon environment variables"
  kubernetesMonitoring.serviceAccountName:
    type: string
    description: "Name of the ServiceAccount to assign to the ActiveGate Pods"
    title: "Kubemon service-account name"

  routing.enabled:
    type: boolean
    description: "Enables automatic Routing for your cluster"
    title: "Enable Routing"
    default: true
  routing.replicas:
    type: integer
    description: "Number of replicas for the Routing pods"
    title: "Routing Replicas"
    default: 1
  routing.group:
    type: string
    description: "Set activation group for this ActiveGate"
    title: "Routing activation group"
  routing.customProperties.value:
    type: string
    description: "Add a custom properties file by providing it as a value"
    title: "Routing custom properties as value"
  routing.customProperties.valueFrom:
    type: string
    description: "Add a custom properties file by providing it as a reference"
    title: "Routing custom properties as reference"
  routing.resources:
    type: string
    description: "Resource settings for ActiveGate container"
    title: "Routing resources"
  routing.nodeSelector:
    type: string
    description: "Set node selector to control on which nodes these ActiveGate pods will be deployed"
    title: "Routing node selector"
  routing.tolerations:
    type: string
    description: "Tolerations to include with this ActiveGate StatefulSet"
    title: "Routing tolerations"
  routing.labels:
    type: string
    description: "Labels are customer defined labels for these ActiveGate Pods to structure workloads as desired"
    title: "Routing labels"
  routing.args:
    type: string
    description: "Arguments to add to these ActiveGate instances"
    title: "Routing arguments"
  routing.env:
    type: string
    description: "Additional environment variables to add to these ActiveGate Pods"
    title: "Routing environment variables"
  routing.serviceAccountName:
    type: string
    description: "Name of the ServiceAccount to assign to the ActiveGate Pods"
    title: "Routing service-account name"

  deployerHelm.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE

required:
  - name
  - namespace
  - apiUrl
  - apiToken
  - paasToken
  - crdApplied