# Copyright 2020 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "0.1.0"
  publishedVersionMetadata:
    releaseNote: >-
      v0.1.0

      Features
      * Initial release of the Dynatrace Operator
    releaseTypes:
      - Feature
    recommended: true

  managedUpdates:
    kalmSupported: true

  images:
    "":
      properties:
        operator.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  apiUrl:
    type: string
    description: The Dynatrace api url including `/api` path at the end
    title: API URL
  apiToken:
    type: string
    description: The API token from your Dynatrace environment
    title: API Token
    x-google-marketplace:
      type: MASKED_FIELD
  paasToken:
    type: string
    description: The PaaS token from your Dynatrace environment
    title: PaaS Token
    x-google-marketplace:
      type: MASKED_FIELD
  skipCertCheck: false
    type: boolean
    description: "Disable certificate validation checks for installer download and API communication"
    default: false
    title: "Skip certificate check"
  proxy:
    type: string
    description: "Configures a proxy for the Agent, AgentDownload, ActiveGate and the Operator. Either provide the proxy URL directly at 'value' or create a secret with a field 'proxy' which holds your encrypted proxy URL"
    title: "Define a proxy"
  trustedCAs:
    type: string
    description: "Adds the provided CA certificates to the Operator and the OneAgent. Provide the name of the configmap which holds your .pem in a field called 'certs'. If this is not set the default embedded certificates on the images will be used"
    title: "Add custom CA certificates"
  networkZone:
    type: string
    description: "Sets a network zone for the given OneAgent or ActiveGates"
    title: "Network zone"
  kubernetesMonitoring.enabled:
    type: boolean
    description: "Enables automatic Kubernetes monitoring for your cluster"
    title: "Enable Kubernetes monitoring"
    default: true
  kubernetesMonitoring.replicas:
    type: integer
    description: "Number of replicas for the Kubernetes monitoring pods"
    title: "Replicas"
    default: 1
  activeGate.image:
    type: string
    description: "The location from where to grab the Dynatrace ActiveGate image - default for Kubernetes is ToDo"
    title: Custom ActiveGate image location
  activeGate.disableActiveGateUpdate:
    type: boolean
    description: "Disables automatic restarts of ActiveGate pods in case a new version is available"
    default: false
    title: "Disable automatic ActiveGate updates"
  deployerHelm.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  operatorServiceAccount:
    type: string
    title: Service account used by the Dynatrace Operator
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used by the Dynatrace Operator
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - dynatrace.com
                  resources:
                    - dynakubes
                  verbs:
                    - get
                    - list
                    - watch
                    - update
                    - create
                - apiGroups:
                    - dynatrace.com
                  resources:
                    - dynakubes/finalizers
                    - dynakubes/status
                  verbs:
                    - update
                - apiGroups:
                    - apps
                  resources:
                    - replicasets
                    - deployments
                  verbs:
                    - get
                    - list
                    - watch
                - apiGroups:
                    - apps
                  resources:
                    - deployments/finalizers
                  verbs:
                    - update
                - apiGroups:
                    - ""
                  resources:
                    - configmaps
                  verbs:
                    - get
                    - list
                    - watch
                    - create
                    - update
                    - delete
                - apiGroups:
                    - ""
                  resources:
                    - pods
                  verbs:
                    - get
                    - list
                    - watch
                    - delete
                    - create
                - apiGroups:
                    - ""
                  resources:
                    - secrets
                  verbs:
                    - get
                    - list
                    - watch
                - apiGroups:
                    - monitoring.coreos.com
                  resources:
                    - servicemonitors
                  verbs:
                    - get
                    - create
                - apiGroups:
                    - ""
                  resources:
                    - services
                  verbs:
                    - create
  kubernetesMonitoringServiceAccount:
    type: string
    title: Service account used by the Dynatrace Kubernetes Monitoring
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used by the Dynatrace Kubernetes Monitoring
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                - ""
                - batch
                - apps
                - apps.openshift.io
                resources:
                  - nodes
                  - pods
                  - namespaces
                  - deployments
                  - replicasets
                  - deploymentconfigs
                  - replicationcontrollers
                  - jobs
                  - cronjobs
                  - statefulsets
                  - daemonsets
                  - events
                  - resourcequotas
                  - pods/proxy
                verbs:
                  - list
                  - watch
                  - get
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-kubernetes-monitoring
                verbs:
                  - use
  configurationServiceAccount:
    type: string
    title: Service account used to configure the Dynatrace Operator
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used to configure the Dynatrace Operator
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - namespaces
                resourceNames:
                  - "kube-system"
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - dynatrace.com
                resources:
                  - dynakubes
                verbs:
                  - get
                  - list
                  - watch
                  - update
                  - create
              - apiGroups:
                  - dynatrace.com
                resources:
                  - dynakubes/finalizers
                  - dynakubes/status
                verbs:
                  - update
              - apiGroups:
                  - apps
                resources:
                  - statefulsets
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - delete
              - apiGroups:
                  - apps
                resources:
                  - replicasets
                  - deployments
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - apps
                resources:
                  - deployments/finalizers
                verbs:
                  - update
              - apiGroups:
                  - ""
                resources:
                  - configmaps
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - delete
              - apiGroups:
                  - ""
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
                  - delete
                  - create
              - apiGroups:
                  - ""
                resources:
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
              - apiGroups:
                  - monitoring.coreos.com
                resources:
                  - servicemonitors
                verbs:
                  - get
                  - create
              - apiGroups:
                  - ""
                resources:
                  - services
                verbs:
                  - create
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-operator
                verbs:
                  - use

required:
  - name
  - namespace
  - apiUrl
  - apiToken
  - paasToken
  - operatorServiceAccount
  - kubernetesMonitoringServiceAccount
  - configurationServiceAccount
