# Copyright 2019 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
name: dynatrace-oneagent-operator
description: The Dynatrace OneAgent Operator Helm chart for Google Kubernetes Engine
home: https://www.dynatrace.com/
type: application
version: 0.7
appVersion: 0.7
maintainers:
  - name: DTMad
    email: marco.mader@dynatrace.com
  - name: lrgar
    email: luis.garcia@dynatrace.com
  - name: mmayr-at
    email: michael.mayr@dynatrace.com
sources:
  - https://github.com/Dynatrace/helm-charts
