# Copyright 2019 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mode: "fullstack"

operator:
  image: ""

oneagent:
  name: "oneagent"
  apiUrl: ""
  image: ""
  args:
    - --set-app-log-content-access=true
  env:
    - name: ONEAGENT_ENABLE_VOLUME_STORAGE
      value: "true"
  nodeSelector: {}
  labels: {}
  skipCertCheck: false
  disableAgentUpdate: false
  enableIstio: false
  dnsPolicy: ""
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  #   limits:
  #     cpu: 300m
  #     memory: 1.5Gi
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  waitReadySeconds: null
  priorityClassName: ""
  serviceAccountName: ""
  unprivilegedServiceAccountName: ""
  proxy: ""
  trustedCAs: ""
  networkZone: ""
  useUnprivilegedMode: false
  useImmutableImage: false
  agentVersion: ""
  customPullSecret: ""
  flavor: ""

secret:
  apiToken: ""
  paasToken: ""

deployerHelm:
  image: ""
