# Copyright 2019 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "0.9.0"
  publishedVersionMetadata:
    releaseNote: >-
      v0.9.0

      Features
        * Provide Prometheus metrics for the Operator pod on port 8080, and Webhook Pod on ports 8383 and 8484 (#305)
        * Control whether the init container crashes in case of download failures through the oneagent.dynatrace.com/failure-policy: fail Pod annotation, off by default (#288)
        * Regardless of the annotation, if the unzip operation fails, a file package.zip will be included on the target directory for debugging purposes.
        * Resource limits and requests for the OneAgentAPM initContainer are configurable on the .spec.resources field (#332)
        * Early Adopter: support full-stack OneAgent running on unprivileged mode (#324, #333)
      Bug fixes
        * Logged errors when API token is missing on OneAgentAPM's secret (#298)
        * Fixed printing the name of the used token secret for OneAgent instances (311)
        * Fixed setting instances metadata when auto-update is disabled (#313)
        * Fixed logging problem - incorrect stackdriver severity on GCP (#318)
      Other changes
        * Added support for immutable OneAgent images - waiting for support on Dynatrace cluster (#300, #286, #290, #301)
        * Added check if cluster and agent versions are compatible with immutable images (#314, #334)
        * Immutable image mode is disabled when a custom installer URL annotation is set, or .spec.useImmutableImage is false (#306)
        * Pod and node metadata added for the OneAgent (#294, #295, #308, #325, #326)
        * Code cleanup to remove unused functions, variables and beautify the code (#302)
        * Sped up TravisCI duration (#310, #312)
        * Upgrade to Go 1.15 (#310)
        * Add linter to TravisCI pipeline (#316)
        * App-only init container will log an warning when the full-stack OneAgent has been injected on it (#323)
        * Improve error message when OneAgentAPM is missing (#327)
        * Improve descriptions on cr.yaml example (#328)
    releaseTypes:
      - Feature
    recommended: true

  managedUpdates:
    kalmSupported: true

  images:
    "":
      properties:
        operator.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  mode:
    type: string
    description: Either fullstack for full monitoring or apm for application only monitoring
    title: Monitoring mode
    default: fullstack
    enum:
      - fullstack
      - apm
  oneagent.apiUrl:
    type: string
    description: The Dynatrace api url including `/api` path at the end
    title: API URL
  secret.apiToken:
    type: string
    description: The API token from your Dynatrace environment
    title: API Token
    x-google-marketplace:
      type: MASKED_FIELD
  secret.paasToken:
    type: string
    description: The PaaS token from your Dynatrace environment
    title: PaaS Token
    x-google-marketplace:
      type: MASKED_FIELD
  oneagent.name:
    type: string
    default: oneagent
    description: The name of the oneagent custom resource
    title: Custom Resource Name
  oneagent.image:
    type: string
    description: "The location from where to grab the Dynatrace OneAgent image - default for Kubernetes is docker.io/dynatrace/oneagent"
    title: Custom OneAgent image location
  oneagent.skipCertCheck:
    type: boolean
    description: "Disable certificate validation checks for installer download and API communication"
    default: false
    title: "Skip certificate check"
  oneagent.disableAgentUpdate:
    type: boolean
    description: "Disables automatic restarts of oneagent pods in case a new version is available"
    default: false
    title: "Disable automatic OneAgent updates"
  oneagent.enableIstio:
    type: boolean
    description: "When enabled, and if Istio is installed on the Kubernetes environment, then the Operator will create the corresponding VirtualService and ServiceEntries objects to allow access to the Dynatrace cluster from the agent."
    default: false
    title: "Enable istio"
  oneagent.dnsPolicy:
    type: string
    description: "DNS Policy for OneAgent pods. Empty for default (ClusterFirst), more at https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy"
    title: "Set custom DNS Policy"
  oneagent.waitReadySeconds:
    type: integer
    description: "Define the time to wait until OneAgent pod is ready after update - defaults to 300s"
    title: "Wait seconds until ready"
  oneagent.priorityClassName:
    type: string
    description: "Priority class to assign to OneAgent pods, more at https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/"
    title: "Assign priority class to OneAgent pods"
  oneagent.proxy:
    type: string
    description: "Configures a proxy for the Agent, AgentDownload and the Operator. Either provide the proxy URL directly at 'value' or create a secret with a field 'proxy' which holds your encrypted proxy URL"
    title: "Define a proxy"
  oneagent.trustedCAs:
    type: string
    description: "Adds the provided CA certficates to the Operator and the OneAgent. Provide the name of the configmap which holds your .pem in a field called 'certs'. If this is not set the default embedded certificates on the images will be used"
    title: "Add custom CA certificates"
  oneagent.networkZone:
    type: string
    description: "Configures a network zone for your OneAgents"
    title: "Network zone"
  oneagent.useUnprivilegedMode:
    type: boolean
    description: "Early Adopter: support full-stack OneAgent running on unprivileged mode"
    title: "Early Adopter: run unprivileged"
    default: false
  oneagent.useImmutableImage:
    type: boolean
    description: "If set (and onagent.image is empty) the immutable OneAgent image will be used"
    title: "Use immutable OneAgent image"
    default: false
  deployerHelm.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  webhookServiceAccount:
    type: string
    title: Service account used by the Dynatrace OneAgent Operator's Webhook
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used by the Dynatrace OneAgent Operator's Webhook
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - ""
                resources:
                  - namespaces
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - admissionregistration.k8s.io
                resources:
                  - mutatingwebhookconfigurations
                verbs:
                  - list
                  - create
                  - watch
              - apiGroups:
                  - admissionregistration.k8s.io
                resources:
                  - mutatingwebhookconfigurations
                resourceNames:
                  - dynatrace-oneagent-webhook
                verbs:
                  - get
                  - update
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - ""
                resources:
                  - services
                  - configmaps
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
              - apiGroups:
                  - ""
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent-webhook
                verbs:
                  - use
  operatorServiceAccount:
    type: string
    title: Service account used by the Dynatrace OneAgent Operator
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used by the Dynatrace OneAgent Operator
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - nodes
                  - namespaces
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - ""
                resources:
                  - secrets
                verbs:
                  - create
              - apiGroups:
                  - ""
                resources:
                  - secrets
                resourceNames:
                  - dynatrace-oneagent-config
                  - dynatrace-oneagent-pull-secret
                verbs:
                  - get
                  - update
                  - delete
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - watch
                  - update
              - apiGroups:
                  - apps
                resources:
                  - daemonsets
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - delete
              - apiGroups:
                  - apps
                resources:
                  - replicasets
                  - deployments
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - apps
                resources:
                  - deployments/finalizers
                verbs:
                  - update
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - configmaps
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - delete
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
                  - delete
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - monitoring.coreos.com
                resources:
                  - servicemonitors
                verbs:
                  - get
                  - create
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents/finalizers
                  - oneagents/status
                  - oneagentapms/finalizers
                  - oneagentapms/status
                verbs:
                  - update
              - apiGroups:
                  - networking.istio.io
                resources:
                  - serviceentries
                  - virtualservices
                verbs:
                  - get
                  - list
                  - create
                  - update
                  - delete
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent-operator
                verbs:
                  - use
  oneagentServiceAccount:
    type: string
    title: Service account used by the Dynatrace OneAgent
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used by the Dynatrace OneAgent
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent
                verbs:
                  - use
  oneagentUnprivilegedServiceAccount:
    type: string
    title: Service account used by the unprivileged Dynatrace OneAgent
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used by the unprivileged Dynatrace OneAgent
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent-unprivileged
                verbs:
                  - use
  configurationServiceAccount:
    type: string
    title: Service account used to configure the Dynatrace OneAgent Operator
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account used to configure the Dynatrace OneAgent Operator
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - create
                  - patch
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                verbs:
                  - get
                  - list
                  - create
                  - patch
              - apiGroups:
                  - apiextensions.k8s.io
                resources:
                  - customresourcedefinitions
                verbs:
                  - get
                  - list
                  - create
                  - patch
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - watch
                  - update
                  - patch
              - apiGroups:
                  - app.k8s.io
                resources:
                  - applications
                verbs:
                  - get
                  - list
required:
  - name
  - namespace
  - oneagent.apiUrl
  - secret.apiToken
  - secret.paasToken
  - operatorServiceAccount
  - oneagentServiceAccount
  - configurationServiceAccount
  - webhookServiceAccount
  - oneagentUnprivilegedServiceAccount
