# Copyright 2019 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "0.8.0"
  publishedVersionMetadata:
    releaseNote: >-
      v0.8.0

      New: Kubernetes Webhook for OneAgent injection on application-only mode
      This automates the deployment of Dynatrace's application-only injection at container runtime, including a new init container, and other required configuration.

      For this feature, we've also added a new Custom Resource Definition, OneAgentAPM, where you can configure the tenant and credentials to use for the injection.

      The feature can be enabled by creating an OneAgentAPM object, and then adding a label oneagent.dynatrace.com/instance: <OneAgentAPM object name> to each namespace you want to monitor. All Pods created from now on that belong to those namespaces will now be processed by Operator webhook.

      The Operator will:

      Add an initContainer to each Pod to be monitored, in charge of downloading the OneAgent app-only package.
      Configure the required environment variables and volumes on each container for them to have injection.
      Replicate the credentials to monitored namespaces, so that they are available for the initContainer.


      Changelog

      Features
      Implement webhook to inject the OneAgent in App-only mode (#234, #237, #239, #250)
      This feature can be enabled by setting the label oneagent.dynatrace.com/instance: <oneagentapm-object-name> on the namespaces to monitor.
      CA and server certificates are generated for the webhook by the Operator, and renewed automatically after 365 and 7 days, respectively (#244)
      OneAgent app-only package and logs will be stored on /opt/dynatrace/oneagent-paas inside the containers by default. It can be configured with the oneagent.dynatrace.com/install-path annotation on Pods (#251)
      OneAgent app-only package will be downloaded from the provided tenant by default. It can be configured with the oneagent.dynatrace.com/installer-url annotation on Pods (#258, #264)
      Certificates location can be configured on the webhook server with the --certs-dir, --cert, and --cert-key command line arguments (#261)
      Added a setting to configure a NetworkZone via the CR (#270)

      Bug fixes
      Phase now gets set to 'Deploying' while the OneAgent gets updated (#267)

      Other changes
      Removed kubernetes.yaml and openshift.yaml from master and generate them with kustomize instead
      Updated the Go version from 1.13 to 1.14
      Updated the Operator SDK version from 0.15.0 to 0.17.0
      The different operator and webhook modes are encapsulated in a single binary
      Webhook's init container only downloads 64bits package
      Include Service and MutatingWebhookConfiguration objects in manifests
      Upgrade base image to ubi-minimal:8.2
      Include Operator version as a custom property for hosts
      Ignore hosts that haven't been seen in the last 30 minutes when looking for hosts
      Adjust permissions for the webhook
      Refactor workflow from OneAgent controller
      Automatically update conditions if migrating from earlier Operator versions
      Remove unused metadata from webhook-injected Pods
      Changes in preparation for v0.8.0 release
    releaseTypes:
      - Feature
    recommended: true

  managedUpdates:
    kalmSupported: true

  images:
    "":
      properties:
        operator.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  mode:
    type: string
    description: Either fullstack for full monitoring or apm for application only monitoring
    title: Monitoring mode
    default: fullstack
    enum:
      - fullstack
      - apm
  oneagent.apiUrl:
    type: string
    description: The Dynatrace api url including `/api` path at the end
    title: API URL
  secret.apiToken:
    type: string
    description: The API token from your Dynatrace environment
    title: API Token
    x-google-marketplace:
      type: MASKED_FIELD
  secret.paasToken:
    type: string
    description: The PaaS token from your Dynatrace environment
    title: PaaS Token
    x-google-marketplace:
      type: MASKED_FIELD
  oneagent.name:
    type: string
    default: oneagent
    description: The name of the oneagent custom resource
    title: Custom Resource Name
  oneagent.image:
    type: string
    description: "The location from where to grab the Dynatrace OneAgent image - default for Kubernetes is docker.io/dynatrace/oneagent"
    title: Custom OneAgent image location
  oneagent.skipCertCheck:
    type: boolean
    description: "Disable certificate validation checks for installer download and API communication"
    default: false
    title: "Skip certificate check"
  oneagent.disableAgentUpdate:
    type: boolean
    description: "Disables automatic restarts of oneagent pods in case a new version is available"
    default: false
    title: "Disable automatic OneAgent updates"
  oneagent.enableIstio:
    type: boolean
    description: "When enabled, and if Istio is installed on the Kubernetes environment, then the Operator will create the corresponding VirtualService and ServiceEntries objects to allow access to the Dynatrace cluster from the agent."
    default: false
    title: "Enable istio"
  oneagent.dnsPolicy:
    type: string
    description: "DNS Policy for OneAgent pods. Empty for default (ClusterFirst), more at https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy"
    title: "Set custom DNS Policy"
  oneagent.waitReadySeconds:
    type: integer
    description: "Define the time to wait until OneAgent pod is ready after update - defaults to 300s"
    title: "Wait seconds until ready"
  oneagent.priorityClassName:
    type: string
    description: "Priority class to assign to OneAgent pods, more at https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/"
    title: "Assign priority class to OneAgent pods"
  oneagent.proxy:
    type: string
    description: "Configures a proxy for the Agent, AgentDownload and the Operator. Either provide the proxy URL directly at 'value' or create a secret with a field 'proxy' which holds your encrypted proxy URL"
    title: "Define a proxy"
  oneagent.trustedCAs:
    type: string
    description: "Adds the provided CA certficates to the Operator and the OneAgent. Provide the name of the configmap which holds your .pem in a field called 'certs'. If this is not set the default embedded certificates on the images will be used"
    title: "Add custom CA certificates"
  deployerHelm.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  webhookServiceAccount:
    type: string
    title: Service account used by the Dynatrace OneAgent Operator's Webhook
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - ""
                resources:
                  - namespaces
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - admissionregistration.k8s.io
                resources:
                  - mutatingwebhookconfigurations
                verbs:
                  - list
                  - create
                  - watch
              - apiGroups:
                  - admissionregistration.k8s.io
                resources:
                  - mutatingwebhookconfigurations
                resourceNames:
                  - dynatrace-oneagent-webhook
                verbs:
                  - get
                  - update
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - ""
                resources:
                  - services
                  - configmaps
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
              - apiGroups:
                  - ""
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent-webhook
                verbs:
                  - use
  operatorServiceAccount:
    type: string
    title: Service account used by the Dynatrace OneAgent Operator
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - nodes
                  - namespaces
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - ""
                resources:
                  - secrets
                verbs:
                  - create
              - apiGroups:
                  - ""
                resources:
                  - secrets
                resourceNames:
                  - dynatrace-oneagent-config
                verbs:
                  - get
                  - update
                  - delete
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - watch
                  - update
              - apiGroups:
                  - apps
                resources:
                  - daemonsets
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - delete
              - apiGroups:
                  - apps
                resources:
                  - replicasets
                  - deployments
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - apps
                resources:
                  - deployments/finalizers
                verbs:
                  - update
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - configmaps
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - delete
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
                  - delete
              - apiGroups:
                  - "" # "" indicates the core API group
                resources:
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - monitoring.coreos.com
                resources:
                  - servicemonitors
                verbs:
                  - get
                  - create
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents/finalizers
                  - oneagents/status
                  - oneagentapms/finalizers
                  - oneagentapms/status
                verbs:
                  - update
              - apiGroups:
                  - networking.istio.io
                resources:
                  - serviceentries
                  - virtualservices
                verbs:
                  - get
                  - list
                  - create
                  - update
                  - delete
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent-operator
                verbs:
                  - use
  oneagentServiceAccount:
    type: string
    title: Service account used by the Dynatrace OneAgent
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                resourceNames:
                  - dynatrace-oneagent
                verbs:
                  - use
  configurationServiceAccount:
    type: string
    title: Service account used to configure the Dynatrace OneAgent Operator
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - create
                  - patch
              - apiGroups:
                  - policy
                resources:
                  - podsecuritypolicies
                verbs:
                  - get
                  - list
                  - create
                  - patch
              - apiGroups:
                  - apiextensions.k8s.io
                resources:
                  - customresourcedefinitions
                verbs:
                  - get
                  - list
                  - create
                  - patch
              - apiGroups:
                  - dynatrace.com
                resources:
                  - oneagents
                  - oneagentapms
                verbs:
                  - get
                  - list
                  - watch
                  - update
                  - patch
              - apiGroups:
                  - app.k8s.io
                resources:
                  - applications
                verbs:
                  - get
                  - list
required:
  - name
  - namespace
  - oneagent.apiUrl
  - secret.apiToken
  - secret.paasToken
  - operatorServiceAccount
  - oneagentServiceAccount
  - configurationServiceAccount
  - webhookServiceAccount
