# Copyright 2020 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "dynatrace-operator.labels" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - "/bin/bash"
            - "-ec"
            - |
              uid=$(kubectl get application {{ .Release.Name }} -n {{ .Release.Namespace }} -o jsonpath='{.metadata.uid}')

              echo "Applying mutatingWebhookConfiguration"
              sed "s/##UID##/${uid}/g" /objects/mutatingWebhookConfiguration.yaml | kubectl apply -f -
              echo "Applying CSI driver config"
              sed "s/##UID##/${uid}/g" /objects/csidriver.yaml | kubectl apply -f -
              
              echo "Creating CRD definition"
              mkdir /tmp/crd
              sed "s/##UID##/${uid}/g" /crd1/dynakube_crd.yaml.1 > /tmp/crd/crd.yaml
              tail -c +3 /crd2/dynakube_crd.yaml.2 >> /tmp/crd/crd.yaml
              kubectl apply -f /tmp/crd/crd.yaml

              echo "Setup kubernetes-monitoring clusterrole"
              sed "s/##UID##/${uid}/g" /objects/kubernetes-monitoring-serviceaccount.yaml | kubectl apply -f -
              sed "s/##UID##/${uid}/g" /objects/kubernetes-monitoring-clusterrole.yaml | kubectl apply -f -
              sed "s/##UID##/${uid}/g" /objects/kubernetes-monitoring-clusterrolebinding.yaml | kubectl apply -f -

              echo "Create service accounts needed by fullstack spec"
              sed "s/##UID##/${uid}/g" /objects/oneagent-serviceaccount.yaml | kubectl apply -f -
              sed "s/##UID##/${uid}/g" /objects/oneagent-unprivileged-serviceaccount.yaml | kubectl apply -f -

              sleep 5
              echo "Applying dynakube"
              sed "s/##UID##/${uid}/g" /objects/dynakube.yaml | kubectl apply -f -
          image: {{ .Values.deployerHelm.image }}
          imagePullPolicy: Always
          name: objects-create
          volumeMounts:
            - name: object-configmap
              mountPath: /objects/
            - name: object-configmap-crd1
              mountPath: /crd1/
            - name: object-configmap-crd2
              mountPath: /crd2/
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: {{ .Values.configurationServiceAccount }}
      volumes:
        - name: object-configmap
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: object-configmap-crd1
          configMap:
            name: {{ .Release.Name }}-configmap-crd1
        - name: object-configmap-crd2
          configMap:
            name: {{ .Release.Name }}-configmap-crd2
