# Copyright 2019 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "0.10.2"
  publishedVersionMetadata:
    releaseNote: >-
      v0.10.2

      Other changes
        * Removed the CustomResourceDefinition from the Helm chart
        * Removed PodSecurityPolicies since they got removed with Kubernetes 1.22
        * Updated the apiVersion of the CRD from v1beta1 to v1 since v1beta1 got removed with Kubernetes 1.22
    releaseTypes:
      - BugFix
    recommended: true

  managedUpdates:
    kalmSupported: true

  images:
    "":
      properties:
        operator.image:
          type: FULL

  deployerServiceAccount:
    description: >
      Service account used to configure the Dynatrace OneAgent Operator
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
              - dynatrace.com
            resources:
              - oneagents
              - oneagentapms
            verbs:
              - get
              - list
              - create
              - patch
          - apiGroups:
              - apiextensions.k8s.io
            resources:
              - customresourcedefinitions
            verbs:
              - get
              - list
              - create
              - patch
          - apiGroups:
              - dynatrace.com
            resources:
              - oneagents
              - oneagentapms
            verbs:
              - get
              - list
              - watch
              - update
              - patch
          - apiGroups:
              - app.k8s.io
            resources:
              - applications
            verbs:
              - get
              - list
          - apiGroups:
              - admissionregistration.k8s.io
            resources:
              - mutatingwebhookconfigurations
            verbs:
              - list
              - create
              - watch
          - apiGroups:
              - admissionregistration.k8s.io
            resources:
              - mutatingwebhookconfigurations
            resourceNames:
              - dynatrace-oneagent-webhook
            verbs:
              - get
              - update
              - patch
          - apiGroups: [""]
            resources:
              - serviceaccounts
            verbs: ["*"]
          - apiGroups:
              - rbac.authorization.k8s.io
            resources:
              - clusterroles
              - clusterrolebindings
            verbs: ["*"]

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  oneagent.apiUrl:
    type: string
    description: The Dynatrace api url including `/api` path at the end
    title: API URL
  secret.apiToken:
    type: string
    description: The API token from your Dynatrace environment
    title: API Token
    x-google-marketplace:
      type: MASKED_FIELD
  secret.paasToken:
    type: string
    description: The PaaS token from your Dynatrace environment
    title: PaaS Token
    x-google-marketplace:
      type: MASKED_FIELD
  crdApplied:
    type: boolean
    description: "Please make sure you have applied the latest CRD by following the instructions in the Github Repository."
    title: "CRD manually applied"
    default: false

  platform:
    type: string
    title: The platform you are deploying on
    description: This should always be set to "google"
    default: google
  deployerHelm.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE

required:
  - name
  - namespace
  - oneagent.apiUrl
  - secret.apiToken
  - secret.paasToken
  - crdApplied
