apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dynakubes.dynatrace.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.apiUrl
    name: ApiUrl
    type: string
  - JSONPath: .spec.tokens
    name: Tokens
    type: string
  - JSONPath: .status.version
    name: Version
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: dynatrace.com
  names:
    kind: DynaKube
    listKind: DynaKubeList
    plural: dynakubes
    singular: dynakube
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DynaKube is the Schema for the DynaKube API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DynaKubeSpec defines the desired state of DynaKube
          properties:
            apiUrl:
              description: Location of the Dynatrace API to connect to, including
                your specific environment ID
              type: string
            customPullSecret:
              description: 'Optional: Pull secret for your private registry'
              type: string
            kubernetesMonitoring:
              description: Enables Kubernetes Monitoring
              properties:
                activeGateVersion:
                  description: 'Optional: If specified, indicates the ActiveGate version
                    to use Defaults to latest Example: {major.minor.release} - 1.200.0'
                  type: string
                disableActivegateUpdate:
                  description: Disable automatic restarts of Activegate pods in case
                    a new version is available
                  type: boolean
                dnsPolicy:
                  description: 'Optional: Sets DNS Policy for the ActiveGate pods'
                  type: string
                enabled:
                  description: Enables Kubernetes Monitoring
                  type: boolean
                image:
                  description: 'Optional: the ActiveGate container image Defaults
                    to docker.io/dynatrace/activegate:latest for Kubernetes and to
                    registry.connect.redhat.com/dynatrace/activegate for OpenShift'
                  type: string
                kubernetesApiEndpoint:
                  description: The public API endpoint of the Kubernetes instance
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  description: 'Optional: Adds additional labels for the ActiveGate
                    pods'
                  type: object
                nodeSelector:
                  additionalProperties:
                    type: string
                  description: 'Optional: Node selector to control the selection of
                    nodes'
                  type: object
                priorityClassName:
                  description: 'Optional: If specified, indicates the pod''s priority.
                    Name must be defined by creating a PriorityClass object with that
                    name.'
                  type: string
                replicas:
                  description: Amount of replicas for your DynaKube
                  format: int32
                  type: integer
                resources:
                  description: 'Optional: define resources requests and limits for
                    single ActiveGate pods'
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                serviceAccountName:
                  description: 'Optional: set custom Service Account Name used with
                    ActiveGate pods'
                  type: string
                tolerations:
                  description: 'Optional: set tolerations for the ActiveGatePods pods'
                  items:
                    description: The pod this Toleration is attached to tolerates
                      any taint that matches the triple <key,value,effect> using the
                      matching operator <operator>.
                    properties:
                      effect:
                        description: Effect indicates the taint effect to match. Empty
                          means match all taint effects. When specified, allowed values
                          are NoSchedule, PreferNoSchedule and NoExecute.
                        type: string
                      key:
                        description: Key is the taint key that the toleration applies
                          to. Empty means match all taint keys. If the key is empty,
                          operator must be Exists; this combination means to match
                          all values and all keys.
                        type: string
                      operator:
                        description: Operator represents a key's relationship to the
                          value. Valid operators are Exists and Equal. Defaults to
                          Equal. Exists is equivalent to wildcard for value, so that
                          a pod can tolerate all taints of a particular category.
                        type: string
                      tolerationSeconds:
                        description: TolerationSeconds represents the period of time
                          the toleration (which must be of effect NoExecute, otherwise
                          this field is ignored) tolerates the taint. By default,
                          it is not set, which means tolerate the taint forever (do
                          not evict). Zero and negative values will be treated as
                          0 (evict immediately) by the system.
                        format: int64
                        type: integer
                      value:
                        description: Value is the taint value the toleration matches
                          to. If the operator is Exists, the value should be empty,
                          otherwise just a regular string.
                        type: string
                    type: object
                  type: array
              type: object
            networkZone:
              description: 'Optional: Sets Network Zone for OneAgent and ActiveGate
                pods'
              type: string
            proxy:
              description: 'Optional: Set custom proxy settings either directly or
                from a secret with the field ''proxy'''
              properties:
                value:
                  type: string
                valueFrom:
                  type: string
              type: object
            skipCertCheck:
              description: Disable certificate validation checks for installer download
                and API communication
              type: boolean
            tokens:
              description: Credentials for the DynaKube to connect back to Dynatrace.
              type: string
            trustedCAs:
              description: 'Optional: Adds custom RootCAs from a configmap'
              type: string
          required:
          - apiUrl
          type: object
        status:
          description: DynaKubeStatus defines the observed state of DynaKube
          properties:
            conditions:
              description: Conditions includes status about the current state of the
                instance
              items:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            lastAPITokenProbeTimestamp:
              description: LastAPITokenProbeTimestamp tracks when the last request
                for the API token validity was sent
              format: date-time
              type: string
            lastPaaSTokenProbeTimestamp:
              description: LastPaaSTokenProbeTimestamp tracks when the last request
                for the PaaS token validity was sent
              format: date-time
              type: string
            phase:
              description: Defines the current state (Running, Updating, Error, ...)
              type: string
            updatedTimestamp:
              description: UpdatedTimestamp indicates when the instance was last updated
              format: date-time
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
