name: Changelog generation

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: "Dynatrace/dynatrace-operator/actions/changelog-ci@master"
        with: 
          config_file: "Dynatrace/dynatrace-operator/actions/changelog-ci/changelog-ci-config.json"
